### ISSUE TITLE
[Q] myserious error messages talking about clipboard

### ISSUE THREAD

**Issue by willem640** [drmly/drmly#2]
why does it constantly check my clipboard for youtube urls

**Comment by willem640** [comment]
I was just wonderin'

**Comment by willem640** [comment]
looking at the source, it seems to constantly check your clipboard for youtube urls (file: clipboard.go), but what does it do with the youtube videos? it outputs got: youtube.com/watch?v=sAmPlEuRl when i copy a valid youtube url

**Comment by TableMountain** [comment]
yes, you can disable that feature by deleting clipboard.go. It's just for quick starting jobs so it's only for convenience.

**Comment by willem640** [comment]
Okay, cool

**Comment by willem640** [comment]
Seemed strange at first but your explanation makes it all so clear now
